# Build Lazarus with Travis CI
language: c
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq build-essential
install:
- sudo apt-get update -qq
- sudo apt-get install -qq gcc-multilib
script: make
